// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOTVd9bfgXvnfxx9muh2OvKgKy0SiIi4c',
    appId: '1:197295938873:web:74e7ae527e1202a20d9ce8',
    messagingSenderId: '197295938873',
    projectId: 'find-job-project-ffaa6',
    authDomain: 'find-job-project-ffaa6.firebaseapp.com',
    storageBucket: 'find-job-project-ffaa6.firebasestorage.app',
    measurementId: 'G-LRV03V46XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsH3D_dgKmGOlCEuq66qBJ3suxn_B95go',
    appId: '1:197295938873:android:cce49678886888680d9ce8',
    messagingSenderId: '197295938873',
    projectId: 'find-job-project-ffaa6',
    storageBucket: 'find-job-project-ffaa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFrrgqSE6g8Fg_eC68kWOPvxpxfgJiAX8',
    appId: '1:197295938873:ios:e7bac6d15724634c0d9ce8',
    messagingSenderId: '197295938873',
    projectId: 'find-job-project-ffaa6',
    storageBucket: 'find-job-project-ffaa6.firebasestorage.app',
    iosBundleId: 'com.example.findJob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFrrgqSE6g8Fg_eC68kWOPvxpxfgJiAX8',
    appId: '1:197295938873:ios:e7bac6d15724634c0d9ce8',
    messagingSenderId: '197295938873',
    projectId: 'find-job-project-ffaa6',
    storageBucket: 'find-job-project-ffaa6.firebasestorage.app',
    iosBundleId: 'com.example.findJob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOTVd9bfgXvnfxx9muh2OvKgKy0SiIi4c',
    appId: '1:197295938873:web:00083dbe4fbf3d290d9ce8',
    messagingSenderId: '197295938873',
    projectId: 'find-job-project-ffaa6',
    authDomain: 'find-job-project-ffaa6.firebaseapp.com',
    storageBucket: 'find-job-project-ffaa6.firebasestorage.app',
    measurementId: 'G-7MKDPYFNPK',
  );
}
